### ISSUE TITLE
Is there a version for KP3S Pro?

### ISSUE THREAD

**Issue by Briones** [RyanT95/KP3S-Prusa#1]
I have a KP3S Pro S1 and I was wondering if this would work for that printer too.

**Comment by RyanT95** [comment]
This should work for the KP3S Pro S1, but you'll be limited to a build volume of 180mm³. The Pro S1 has an increased build volume of 200mm³. You'll be able to edit the file to up the volume to 180mm³, I'll try to add a profile for the Pro S1 if I get a chance.

**Comment by RyanT95** [comment]
@Briones Profile for KP3S Pro S1 added in latest release.
