### ISSUE TITLE
WHY?

### ISSUE THREAD

**Issue by Greeniac** [RyanT95/KP3S-Prusa#3]
KP3S Pro S1, and a benchy is 1:50h in "SUPER SPEED', why!?, like speed is good, but 500 accel is insane, 2k minimum

**Comment by Greeniac** [comment]
a benchy is 44m in my 100mm/s 2.5k profile

**Comment by RyanT95** [comment]
@Greeniac Instead of complaining like a child, why not share your settings so I can update the profile?
