### ISSUE TITLE
PrusaSlicer 2.8

### ISSUE THREAD

**Issue by MSkladanowski** [RyanT95/KP3S-Prusa#6]
Hi, 
Are those profiles working with PrusaSlicer 2.8? I have truble to load them, i have done evrything from instructions.

**Comment by sillent** [comment]
@MSkladanowski hi, 

open Kingroon.ini file, in section [vendor] just add this configuration

```
repo_id = non-prusa-fff
```
should looks like this

```ini
[vendor]
repo_id = non-prusa-fff
```

**Comment by RyanT95** [comment]
@MSkladanowski Hi, this should be fixed in the latest release, which has just been published

**Comment by RyanT95** [comment]
@MSkladanowski Hi, this should be fixed in the latest release, which has just been published
